### ISSUE TITLE
Stuck at creating new project

### ISSUE THREAD

**Issue by nehalist** [sane/sane#200]
Hi,

wanted to try out Sane, but sadly it's stuck when I try to create a new project.
```
PS D:\Node> sane new sanetest
←[90mDetected different versions for sane's locally installed ember-cli (0.2.7) and your global one (4.1.1). Want to use
 sane's one? (y/n):←[39m  (y) y
```

And that's it. Nothing happens afterwards (at least not for quite some time).

Sane version: 0.0.24
OS: Windows 10
Node: 4.1.1
NPM: 2.14.4

**Comment by nehalist** [comment]
Got it to work (re-installed it), but now i got the following error:
```
Sane version: 0.0.24

Setting up Sails project locally.
sails version: 0.11.2
info: Created a new Sails app `server`!
Installed Sails packages for tooling via npm.

Setting up Ember project locally.
ember-cli spawn C:\...\AppData\Roaming\npm\node_modules\sane-cli\node_modules\ember-cli\bin\ember ENOENT
```

**Comment by kriswill** [comment]
`ENOENT` on windows means "no directory entry".  This could be a problem with the full length of the path.  Try installing npm v3, which has redesigned the way it stores module paths to address this problem specifically.

**Comment by nehalist** [comment]
Updated to npm 3.3.4, now I'm getting this error:

```
Sane version: 0.0.24

Setting up Sails project locally.
sails version: 0.11.2
info: Created a new Sails app `server`!
Installing Sails packages for tooling via npm...`npm.cmd i sails-generate-ember-
blueprints lodash pluralize sails-hook-autoreload@~0.11.4 sails-hook-dev@^1.0.0
sails-disk --save` failed with code 1
```

**Comment by kriswill** [comment]
can you make a gist with the contents of the npm-debug.log?

**Comment by nehalist** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\*\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'sails-generate-ember-blueprints',
1 verbose cli   'lodash',
1 verbose cli   'pluralize',
1 verbose cli   'sails-hook-autoreload@~0.11.4',
1 verbose cli   'sails-hook-dev@1.0.0',
1 verbose cli   'sails-disk',
1 verbose cli   '--save' ]
2 info using npm@3.3.4
3 info using node@v4.1.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData sails-generate-ember-blueprints
8 silly fetchPackageMetaData lodash
9 silly fetchPackageMetaData pluralize
10 silly fetchPackageMetaData sails-hook-autoreload@~0.11.4
11 silly fetchPackageMetaData sails-hook-dev@1.0.0
12 silly fetchPackageMetaData sails-disk@~0.10.0
13 silly fetchNamedPackageData sails-hook-autoreload
14 silly mapToRegistry name sails-hook-autoreload
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry https://registry.npmjs.org/
17 silly mapToRegistry uri https://registry.npmjs.org/sails-hook-autoreload
18 silly fetchNamedPackageData sails-hook-dev
19 silly mapToRegistry name sails-hook-dev
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/sails-hook-dev
23 silly fetchNamedPackageData sails-disk
24 silly mapToRegistry name sails-disk
25 silly mapToRegistry using default registry
26 silly mapToRegistry registry https://registry.npmjs.org/
27 silly mapToRegistry uri https://registry.npmjs.org/sails-disk
28 silly fetchNamedPackageData sails-generate-ember-blueprints
29 silly mapToRegistry name sails-generate-ember-blueprints
30 silly mapToRegistry using default registry
31 silly mapToRegistry registry https://registry.npmjs.org/
32 silly mapToRegistry uri https://registry.npmjs.org/sails-generate-ember-blueprints
33 silly fetchNamedPackageData lodash
34 silly mapToRegistry name lodash
35 silly mapToRegistry using default registry
36 silly mapToRegistry registry https://registry.npmjs.org/
37 silly mapToRegistry uri https://registry.npmjs.org/lodash
38 silly fetchNamedPackageData pluralize
39 silly mapToRegistry name pluralize
40 silly mapToRegistry using default registry
41 silly mapToRegistry registry https://registry.npmjs.org/
42 silly mapToRegistry uri https://registry.npmjs.org/pluralize
43 verbose request uri https://registry.npmjs.org/sails-generate-ember-blueprints
44 verbose request no auth needed
45 info attempt registry request try #1 at 07:51:24
46 verbose request id d686b3a6d2d9944d
47 verbose etag "ASZAEGI0ZZKS5B1PG4BIWQJCG"
48 http request GET https://registry.npmjs.org/sails-generate-ember-blueprints
49 verbose request uri https://registry.npmjs.org/sails-disk
50 verbose request no auth needed
51 info attempt registry request try #1 at 07:51:24
52 verbose etag "6Z0GD89EM38VUEM4FJ36IIPDC"
53 http request GET https://registry.npmjs.org/sails-disk
54 verbose request uri https://registry.npmjs.org/sails-hook-autoreload
55 verbose request no auth needed
56 info attempt registry request try #1 at 07:51:24
57 verbose etag "8UMLY629I8QLJMWSDA8MJWI56"
58 http request GET https://registry.npmjs.org/sails-hook-autoreload
59 verbose request uri https://registry.npmjs.org/sails-hook-dev
60 verbose request no auth needed
61 info attempt registry request try #1 at 07:51:24
62 verbose etag "8NPVW73BWP7O3R7GLYI2WFKTS"
63 http request GET https://registry.npmjs.org/sails-hook-dev
64 verbose request uri https://registry.npmjs.org/pluralize
65 verbose request no auth needed
66 info attempt registry request try #1 at 07:51:24
67 verbose etag "DMVT7ZWA2GQPTQZOSSQEW67ZZ"
68 http request GET https://registry.npmjs.org/pluralize
69 verbose request uri https://registry.npmjs.org/lodash
70 verbose request no auth needed
71 info attempt registry request try #1 at 07:51:24
72 verbose etag "910BZHK5JI5RLIQBJZKSCO2SD"
73 http request GET https://registry.npmjs.org/lodash
74 http 304 https://registry.npmjs.org/lodash
75 verbose headers { date: 'Mon, 28 Sep 2015 05:51:37 GMT',
75 verbose headers   via: '1.1 varnish',
75 verbose headers   'cache-control': 'max-age=60',
75 verbose headers   etag: '"910BZHK5JI5RLIQBJZKSCO2SD"',
75 verbose headers   age: '31',
75 verbose headers   connection: 'keep-alive',
75 verbose headers   'x-served-by': 'cache-fra1240-FRA',
75 verbose headers   'x-cache': 'HIT',
75 verbose headers   'x-cache-hits': '4',
75 verbose headers   'x-timer': 'S1443419497.988322,VS0,VE0',
75 verbose headers   vary: 'Accept' }
76 silly get cb [ 304,
76 silly get   { date: 'Mon, 28 Sep 2015 05:51:37 GMT',
76 silly get     via: '1.1 varnish',
76 silly get     'cache-control': 'max-age=60',
76 silly get     etag: '"910BZHK5JI5RLIQBJZKSCO2SD"',
76 silly get     age: '31',
76 silly get     connection: 'keep-alive',
76 silly get     'x-served-by': 'cache-fra1240-FRA',
76 silly get     'x-cache': 'HIT',
76 silly get     'x-cache-hits': '4',
76 silly get     'x-timer': 'S1443419497.988322,VS0,VE0',
76 silly get     vary: 'Accept' } ]
77 verbose etag https://registry.npmjs.org/lodash from cache
78 verbose get saving lodash to C:\*\AppData\Roaming\npm-cache\registry.npmjs.org\lodash\.cache.json
79 http 304 https://registry.npmjs.org/pluralize
80 verbose headers { date: 'Mon, 28 Sep 2015 05:51:37 GMT',
80 verbose headers   via: '1.1 varnish',
80 verbose headers   'cache-control': 'max-age=60',
80 verbose headers   etag: '"DMVT7ZWA2GQPTQZOSSQEW67ZZ"',
80 verbose headers   age: '0',
80 verbose headers   connection: 'keep-alive',
80 verbose headers   'x-served-by': 'cache-fra1229-FRA',
80 verbose headers   'x-cache': 'HIT',
80 verbose headers   'x-cache-hits': '1',
80 verbose headers   'x-timer': 'S1443419497.996321,VS0,VE106',
80 verbose headers   vary: 'Accept' }
81 silly get cb [ 304,
81 silly get   { date: 'Mon, 28 Sep 2015 05:51:37 GMT',
81 silly get     via: '1.1 varnish',
81 silly get     'cache-control': 'max-age=60',
81 silly get     etag: '"DMVT7ZWA2GQPTQZOSSQEW67ZZ"',
81 silly get     age: '0',
81 silly get     connection: 'keep-alive',
81 silly get     'x-served-by': 'cache-fra1229-FRA',
81 silly get     'x-cache': 'HIT',
81 silly get     'x-cache-hits': '1',
81 silly get     'x-timer': 'S1443419497.996321,VS0,VE106',
81 silly get     vary: 'Accept' } ]
82 verbose etag https://registry.npmjs.org/pluralize from cache
83 verbose get saving pluralize to C:\*\AppData\Roaming\npm-cache\registry.npmjs.org\pluralize\.cache.json
84 http 304 https://registry.npmjs.org/sails-generate-ember-blueprints
85 verbose headers { date: 'Mon, 28 Sep 2015 05:51:37 GMT',
85 verbose headers   via: '1.1 varnish',
85 verbose headers   'cache-control': 'max-age=60',
85 verbose headers   etag: '"ASZAEGI0ZZKS5B1PG4BIWQJCG"',
85 verbose headers   age: '0',
85 verbose headers   connection: 'keep-alive',
85 verbose headers   'x-served-by': 'cache-fra1239-FRA',
85 verbose headers   'x-cache': 'MISS',
85 verbose headers   'x-cache-hits': '0',
85 verbose headers   'x-timer': 'S1443419497.971401,VS0,VE428',
85 verbose headers   vary: 'Accept' }
86 silly get cb [ 304,
86 silly get   { date: 'Mon, 28 Sep 2015 05:51:37 GMT',
86 silly get     via: '1.1 varnish',
86 silly get     'cache-control': 'max-age=60',
86 silly get     etag: '"ASZAEGI0ZZKS5B1PG4BIWQJCG"',
86 silly get     age: '0',
86 silly get     connection: 'keep-alive',
86 silly get     'x-served-by': 'cache-fra1239-FRA',
86 silly get     'x-cache': 'MISS',
86 silly get     'x-cache-hits': '0',
86 silly get     'x-timer': 'S1443419497.971401,VS0,VE428',
86 silly get     vary: 'Accept' } ]
87 verbose etag https://registry.npmjs.org/sails-generate-ember-blueprints from cache
88 verbose get saving sails-generate-ember-blueprints to C:\*\AppData\Roaming\npm-cache\registry.npmjs.org\sails-generate-ember-blueprints\.cache.json
89 http 304 https://registry.npmjs.org/sails-disk
90 verbose headers { date: 'Mon, 28 Sep 2015 05:51:37 GMT',
90 verbose headers   via: '1.1 varnish',
90 verbose headers   'cache-control': 'max-age=60',
90 verbose headers   etag: '"6Z0GD89EM38VUEM4FJ36IIPDC"',
90 verbose headers   age: '0',
90 verbose headers   connection: 'keep-alive',
90 verbose headers   'x-served-by': 'cache-fra1248-FRA',
90 verbose headers   'x-cache': 'HIT',
90 verbose headers   'x-cache-hits': '1',
90 verbose headers   'x-timer': 'S1443419497.983799,VS0,VE713',
90 verbose headers   vary: 'Accept' }
91 silly get cb [ 304,
91 silly get   { date: 'Mon, 28 Sep 2015 05:51:37 GMT',
91 silly get     via: '1.1 varnish',
91 silly get     'cache-control': 'max-age=60',
91 silly get     etag: '"6Z0GD89EM38VUEM4FJ36IIPDC"',
91 silly get     age: '0',
91 silly get     connection: 'keep-alive',
91 silly get     'x-served-by': 'cache-fra1248-FRA',
91 silly get     'x-cache': 'HIT',
91 silly get     'x-cache-hits': '1',
91 silly get     'x-timer': 'S1443419497.983799,VS0,VE713',
91 silly get     vary: 'Accept' } ]
92 verbose etag https://registry.npmjs.org/sails-disk from cache
93 verbose get saving sails-disk to C:\*\AppData\Roaming\npm-cache\registry.npmjs.org\sails-disk\.cache.json
94 http 304 https://registry.npmjs.org/sails-hook-autoreload
95 verbose headers { date: 'Mon, 28 Sep 2015 05:51:37 GMT',
95 verbose headers   via: '1.1 varnish',
95 verbose headers   'cache-control': 'max-age=60',
95 verbose headers   etag: '"8UMLY629I8QLJMWSDA8MJWI56"',
95 verbose headers   age: '0',
95 verbose headers   connection: 'keep-alive',
95 verbose headers   'x-served-by': 'cache-fra1222-FRA',
95 verbose headers   'x-cache': 'MISS',
95 verbose headers   'x-cache-hits': '0',
95 verbose headers   'x-timer': 'S1443419497.967835,VS0,VE739',
95 verbose headers   vary: 'Accept' }
96 silly get cb [ 304,
96 silly get   { date: 'Mon, 28 Sep 2015 05:51:37 GMT',
96 silly get     via: '1.1 varnish',
96 silly get     'cache-control': 'max-age=60',
96 silly get     etag: '"8UMLY629I8QLJMWSDA8MJWI56"',
96 silly get     age: '0',
96 silly get     connection: 'keep-alive',
96 silly get     'x-served-by': 'cache-fra1222-FRA',
96 silly get     'x-cache': 'MISS',
96 silly get     'x-cache-hits': '0',
96 silly get     'x-timer': 'S1443419497.967835,VS0,VE739',
96 silly get     vary: 'Accept' } ]
97 verbose etag https://registry.npmjs.org/sails-hook-autoreload from cache
98 verbose get saving sails-hook-autoreload to C:\*\AppData\Roaming\npm-cache\registry.npmjs.org\sails-hook-autoreload\.cache.json
99 http 304 https://registry.npmjs.org/sails-hook-dev
100 verbose headers { date: 'Mon, 28 Sep 2015 05:51:37 GMT',
100 verbose headers   via: '1.1 varnish',
100 verbose headers   'cache-control': 'max-age=60',
100 verbose headers   etag: '"8NPVW73BWP7O3R7GLYI2WFKTS"',
100 verbose headers   age: '0',
100 verbose headers   connection: 'keep-alive',
100 verbose headers   'x-served-by': 'cache-fra1222-FRA',
100 verbose headers   'x-cache': 'MISS',
100 verbose headers   'x-cache-hits': '0',
100 verbose headers   'x-timer': 'S1443419497.984061,VS0,VE757',
100 verbose headers   vary: 'Accept' }
101 silly get cb [ 304,
101 silly get   { date: 'Mon, 28 Sep 2015 05:51:37 GMT',
101 silly get     via: '1.1 varnish',
101 silly get     'cache-control': 'max-age=60',
101 silly get     etag: '"8NPVW73BWP7O3R7GLYI2WFKTS"',
101 silly get     age: '0',
101 silly get     connection: 'keep-alive',
101 silly get     'x-served-by': 'cache-fra1222-FRA',
101 silly get     'x-cache': 'MISS',
101 silly get     'x-cache-hits': '0',
101 silly get     'x-timer': 'S1443419497.984061,VS0,VE757',
101 silly get     vary: 'Accept' } ]
102 verbose etag https://registry.npmjs.org/sails-hook-dev from cache
103 verbose get saving sails-hook-dev to C:\*\AppData\Roaming\npm-cache\registry.npmjs.org\sails-hook-dev\.cache.json
104 silly install normalizeTree
105 verbose stack TypeError: Cannot set property 'lodash' of undefined
105 verbose stack     at C:\*\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:94:36
105 verbose stack     at C:\*\AppData\Roaming\npm\node_modules\npm\node_modules\dezalgo\dezalgo.js:17:12
105 verbose stack     at RawTask.call (C:\*\AppData\Roaming\npm\node_modules\npm\node_modules\asap\asap.js:40:19)
105 verbose stack     at flush (C:\*\AppData\Roaming\npm\node_modules\npm\node_modules\asap\raw.js:50:29)
105 verbose stack     at doNTCallback0 (node.js:407:9)
105 verbose stack     at process._tickCallback (node.js:336:13)
106 verbose cwd D:\Node\sane-test\server
107 error Windows_NT 10.0.10240
108 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\*\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "sails-generate-ember-blueprints" "lodash" "pluralize" "sails-hook-autoreload@~0.11.4" "sails-hook-dev@1.0.0" "sails-disk" "--save"
109 error node v4.1.1
110 error npm  v3.3.4
111 error Cannot set property 'lodash' of undefined
112 error If you need help, you may report this error at:
112 error     <https://github.com/npm/npm/issues>
113 verbose exit [ 1, true ]
```
